services:
 postgres:
    image: postgres:16.2
    container_name: db-pass-in
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - 'db:/var/lib/postgresql/data'
