name: CI

on:
  push:
    branches:
      - main

defaults:
 run:
  working-directory: ./api

jobs:
  build-and-push:
    name: 'Build and Push API'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4


    - name: Generate hash
      id: generate_hash
      run: |
        HASH=$(echo $GITHUB_SHA | head -c7)
        echo "hash=$HASH" >> $GITHUB_OUTPUT

    - name: Build docker image
      run: docker build -t ylyra/passin:${{ steps.generate_hash.outputs.hash }} .

    - name: Log into container registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push image
      run: |
        docker push ylyra/passin:${{ steps.generate_hash.outputs.hash }}
        docker tag ylyra/passin:${{ steps.generate_hash.outputs.hash }} ylyra/passin:latest
        docker push ylyra/passin:latest
